### ISSUE TITLE
Runs slow on 1968 PC, reduce memory usage

### ISSUE THREAD

**Issue by Nintron27** [ThePrimeagen/coin-toss-me-daddy#3]
Perhaps we can replace the node portion with pure assembly to improve perf on older machines?

**Comment by ChaseCarlson** [comment]
Support this, we also must convert the rust portion to handwritten ASM if we can

**Comment by omer-biz** [comment]
The next step should be writing some punch cards

**Comment by ThePrimeagen** [comment]
But how do we run this with RSCs?
